### PR TITLE
testing chalxa?

### PR DESCRIPTION
**Pull request by ishan-web**

### CODE REVIEW

**Comment by Aneemes** [comment]
chalxa

**Comment by ishan-web** [comment]
master ko pull request dee

**Comment by Aneemes** [comment]
master xaina
main use garr

**Comment by Aneemes** [comment]
sabai commit xaina hola yesma ta

**Comment by Aneemes** [comment]
kina chaiyo ekkasi

**Comment by ishan-web** [comment]
merge garr na main ma aru

**Comment by Aneemes** [comment]
afai garr na milena?

**Comment by Aneemes** [comment]
merge gareko xa ta main
uptodate xa ru branches sanga

**Comment by ishan-web** [comment]
ani yo k vanya ta

**Comment by ishan-web** [comment]
Sano django project xa kunai ? xa vaney patha ta heram

**Comment by Aneemes** [comment]
xaina sano ta
mero git mai hola dripshop vanne collego project

**Comment by ishan-web** [comment]
ka vettako taile tyo code?, afai garya ta haina tyo teibela

**Comment by Aneemes** [comment]
afai garya ho

**Comment by ishan-web** [comment]
aile audaina hola talai tetiko frontend

**Comment by Aneemes** [comment]
ma fullstack handinchu aile k😒

**Comment by ishan-web** [comment]
You're welcome!

**Comment by ishan-web** [comment]
ignore the django resturant

**Pull request merged**
